theme: jekyll-theme-minimal

title: Parthiv Basu

logo: <div class="LI-profile-badge"  data-version="v1" data-size="medium" data-locale="en_US" data-type="vertical" data-theme="light" data-vanity="parthivbasu"><a class="LI-simple-link" href='https://de.linkedin.com/in/parthivbasu?trk=profile-badge'>Parthiv Basu</a></div>

